### ISSUE TITLE
Prevent malicious links from getting shortened

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/url-shortener#12]
# Tasks
- [x] Download list of malicious urls, update backend DB (PostgreSQL), create server backend endpoint for checking if url is malicious
- [x] Look into setting up some CRON schedule to update the list of malicious urls (source files updates at different times)
- [x] Prevent update of existing short urls to malicious urls
- [x] Prevent duplicate malicious urls from getting added (consolidate sources to be distinct urls)

### Possible Sources
- OpenPhish receives URLs from multiple streams and analyzes them using its proprietary phishing detection algorithms. There are free and commercial offerings available. https://openphish.com/phishing_feeds.html
    - Free Text Download from url (updates every 12 hours) - https://raw.githubusercontent.com/openphish/public_feed/refs/heads/main/feed.txt 
- Blackbook is a historical (black)list of malicious domains created as part of the periodic automated heuristic check (i.e. WHOIS, HTTP, etc.) of newly reported entries from public lists of malicious URLs (currently [CyberCrime](https://cybercrime-tracker.net/), [URLhaus](https://urlhaus.abuse.ch/), [ScumBots](https://twitter.com/scumbots), [Benkow](http://benkow.cc/passwords.php) and [ViriBack](http://tracker.viriback.com/)). Main goal is listing those that are/were malware dedicated (e.g. C&C) - thus, excluding compromised sites. It is supposed to be used for detection of malware beaconing infected clients by inspection of associated DNS traffic, with significant reduce of false-positives. https://github.com/stamparm/blackbook
    - Raw text version - https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt 

## References
- https://github.com/hslatman/awesome-threat-intelligence
- https://zeltser.com/lookup-malicious-websites/
- https://zeltser.com/malicious-ip-blocklists/
