### ISSUE TITLE
Create a history page of links created by logged in users

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/url-shortener#20]
Display created short urls based on the user that is logged in

Implement pagination of created links (e.g 10 per page)

Display account card on homepage (to navigate to history page)

### Tasks
- [x] Create page that shows up only if the user logs in `/history`. Display this link on the homepage component after user logs in 
- [x] On history page, display paginated list of user created links - investigate on how to create the pagination
    - [x] Get query string for `page` => `/history?page=3`. If undefined, get the first page. If defined query for that page 
- [ ] Implement AbortController when fetching data, so that race conditions are resolved
- [x] Have a new backend endpoint for getting history of a given user. Retrieve the user id using the session object stored during login. 
    - [x] Implement rate limiting for this endpoint. Reject any unauthenticated requests with HTTP 404

### References
- Pagination in React - https://www.youtube.com/watch?v=RlzrXSVYPIw
    - Offset DB query by `page number` * `items per page`
    - Append query params to the url `/history?page=2` so we can use this to get the page number
