### ISSUE TITLE
Cache 20% of top read requests for short urls

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/url-shortener#35]
Pareto Principle - https://en.wikipedia.org/wiki/Pareto_principle
- For many outcomes, roughly 80% of consequences come from 20% of causes

Assumption is that 80% of traffic will be for 20% of the most common short urls.
So caching 20% of the most common reads should serve most traffic (80%)

Cache Eviction Policy - Least Recently Used (LRU)
- https://redis.io/blog/cache-eviction-strategies/

In cache object, store short url, long url

Use KeyDB - (Has BSD-3-Clause license)
- Redis is no longer open source - https://redis.io/blog/redis-adopts-dual-source-available-licensing/
OR use Dragonfly
- https://www.dragonflydb.io/docs/getting-started/docker

### Tasks
- [ ] Calculate use case reads / sec to determine how much memory is enough - https://docs.keydb.dev/docs/keydbcli/#performing-an-lru-simulation
- [ ] Setup KeyDB using docker - https://docs.keydb.dev/docs/docker-basics/
- [ ] Update backend endpoints to query cache before querying database (during cache miss)

Setup backend Dockerfile to have multiple process (one running express server in background, one running Keydb)
- https://docs.docker.com/engine/containers/multi-service_container/
- OR run a dockerfile with docker compose up that will run Keydb and express! - https://docs.docker.com/compose/how-tos/production/
- OR run a bash script from the Dockerfile
