### ISSUE TITLE
Fix frontend colors to be consistent and pass contrast checker

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/url-shortener#39]
Color Scheme - https://www.realtimecolors.com/?colors=15090d-faf3f5-f294b3-d4d4d8-75c3c2&fonts=Inter-Inter

```css
:root {
  /* https://www.realtimecolors.com/?colors=15090d-faf3f5-f294b3-d4d4d8-75c3c2&fonts=Inter-Inter */
  --text-color: #15090d;
  --background-color: #faf3f5;
  --primary-color: #f294b3;
  --secondary-color: #d4d4d8;
  --accent-color: #75c3c2;
  --error-color: #a80b0b;
  --success-color: #0e5d3c;
  --link-color: #6b1a35;
  /* ... */
}
```

WebAIM Contrast Checker - https://webaim.org/resources/contrastchecker/

How to Make Your Website Not Ugly: Basic UX for Programmers - Hilary Stohs-Krause - https://www.youtube.com/watch?v=Jf0cjocP8Wk

**The Easy Way to Design Top Tier Websites - https://www.youtube.com/watch?v=qyomWr_C_jA**

world's shortest UI/UX design course - https://www.youtube.com/watch?v=wIuVvCuiJhU

### Tasks
- [x] Implement a common design system for the frontend
- [x] Make all colors used variables in the root css file, so it is easy to change across all pages!
- [x] Fix navigation links color, it currently fails contrast checker
